name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: What package versions are you using?
      placeholder: (You can paste the output of `grep -E "@stl-api/|next|prisma" <package.json`)
    validations:
      required: true
